---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "artemgavrilov"
      - "BupycHuk"
      - "michal-kralik"

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
    reviewers:
      - "artemgavrilov"
      - "BupycHuk"
      - "michal-kralik"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "artemgavrilov"
      - "BupycHuk"
      - "michal-kralik"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "artemgavrilov"
      - "BupycHuk"
      - "michal-kralik"

  - package-ecosystem: "gomod"
    directory: "/api-tests/tools"
    schedule:
      interval: "weekly"
    reviewers:
      - "artemgavrilov"
      - "BupycHuk"
      - "michal-kralik"

  - package-ecosystem: "npm"
    directory: "/cli-tests"
    schedule:
      interval: "weekly"
    reviewers:
      - "artemgavrilov"
      - "BupycHuk"
      - "michal-kralik"
