---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"


  - package-ecosystem: "gomod"
    directory: "/api-tests/tools"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/cli-tests"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/build/docker/client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/build/docker/rpmbuild"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/build/docker/server"
    schedule:
      interval: "weekly"
